import QtQuick 2.0
import SddmComponents 2.0

Rectangle {
    id: root
    width: 1920
    height: 1080
    color: "#161616"

    // ── palette (regenerated by theme-switch via theme.conf) ──
    property color cBg:     "#161616"
    property color cBg1:    "#1e1e1e"
    property color cBg2:    "#262626"
    property color cFg:     "#d4d4d4"
    property color cMuted:  "#6a6a6a"
    property color cAccent: "#8fa1b3"
    property color cRed:    "#bf8b8b"
    property color cGreen:  "#9ab08f"

    TextConstants { id: textConstants }

    Connections {
        target: sddm
        function onLoginFailed() {
            errorMsg.text = "authentication failed"
            errorMsg.color = root.cRed
            password.text = ""
            shakeAnim.restart()
        }
        function onLoginSucceeded() {
            errorMsg.text = "welcome"
            errorMsg.color = root.cGreen
        }
    }

    // ── background: gradient + subtle vignette ──
    Rectangle {
        anchors.fill: parent
        gradient: Gradient {
            GradientStop { position: 0.0; color: "#1c1c1c" }
            GradientStop { position: 0.55; color: "#141414" }
            GradientStop { position: 1.0; color: "#0d0d0d" }
        }
    }

    // faint accent glow top-center
    Rectangle {
        width: 900; height: 900; radius: 450
        anchors.horizontalCenter: parent.horizontalCenter
        anchors.top: parent.top
        anchors.topMargin: -450
        color: root.cAccent
        opacity: 0.05
    }

    // ── time (hero) ──
    Column {
        anchors.horizontalCenter: parent.horizontalCenter
        anchors.top: parent.top
        anchors.topMargin: 150
        spacing: 8

        Text {
            id: clock
            anchors.horizontalCenter: parent.horizontalCenter
            color: root.cFg
            font.family: "JetBrainsMono Nerd Font ExtraBold"
            font.pixelSize: 120
            font.bold: true
            Timer {
                interval: 1000; running: true; repeat: true
                onTriggered: clock.text = Qt.formatDateTime(new Date(), "HH:mm")
            }
            Component.onCompleted: clock.text = Qt.formatDateTime(new Date(), "HH:mm")
        }
        Text {
            anchors.horizontalCenter: parent.horizontalCenter
            color: root.cAccent
            font.family: "JetBrainsMono Nerd Font Medium"
            font.pixelSize: 22
            text: Qt.formatDateTime(new Date(), "dddd · dd MMMM")
        }
    }

    // ── login card ──
    Rectangle {
        id: card
        anchors.centerIn: parent
        anchors.verticalCenterOffset: 90
        width: 440
        height: 320
        radius: 28
        color: Qt.rgba(0.12, 0.12, 0.12, 0.85)
        border.color: Qt.rgba(root.cAccent.r, root.cAccent.g, root.cAccent.b, 0.35)
        border.width: 2

        // shake on failure
        SequentialAnimation {
            id: shakeAnim
            NumberAnimation { target: card; property: "anchors.horizontalCenterOffset"; to: 14;  duration: 50 }
            NumberAnimation { target: card; property: "anchors.horizontalCenterOffset"; to: -14; duration: 50 }
            NumberAnimation { target: card; property: "anchors.horizontalCenterOffset"; to: 8;   duration: 50 }
            NumberAnimation { target: card; property: "anchors.horizontalCenterOffset"; to: 0;   duration: 50 }
        }

        Column {
            anchors.centerIn: parent
            width: parent.width - 64
            spacing: 18

            // avatar
            Rectangle {
                width: 92; height: 92; radius: 46
                anchors.horizontalCenter: parent.horizontalCenter
                color: root.cBg2
                border.color: root.cAccent
                border.width: 3
                Text {
                    anchors.centerIn: parent
                    text: "󰀄"
                    font.family: "JetBrainsMono Nerd Font"
                    font.pixelSize: 44
                    color: root.cAccent
                }
            }

            // username field (editable)
            Rectangle {
                width: parent.width
                height: 50
                radius: 14
                color: Qt.rgba(0.08, 0.08, 0.08, 0.9)
                border.color: username.activeFocus ? root.cAccent : root.cBg2
                border.width: username.activeFocus ? 2 : 1

                Row {
                    anchors.fill: parent
                    anchors.leftMargin: 16
                    spacing: 10
                    Text {
                        anchors.verticalCenter: parent.verticalCenter
                        text: "󰀄"
                        font.family: "JetBrainsMono Nerd Font"
                        font.pixelSize: 16
                        color: root.cMuted
                    }
                    TextInput {
                        id: username
                        width: parent.width - 60
                        anchors.verticalCenter: parent.verticalCenter
                        color: root.cFg
                        font.family: "JetBrainsMono Nerd Font"
                        font.pixelSize: 15
                        clip: true
                        text: userModel.count > 0 ? userModel.lastUser : ""
                        KeyNavigation.tab: password
                        onAccepted: password.forceActiveFocus()
                        Text {
                            anchors.verticalCenter: parent.verticalCenter
                            text: "username"
                            color: root.cMuted
                            font: username.font
                            visible: username.text.length === 0
                        }
                    }
                }
            }

            // password field
            Rectangle {
                width: parent.width
                height: 50
                radius: 14
                color: Qt.rgba(0.08, 0.08, 0.08, 0.9)
                border.color: password.activeFocus ? root.cAccent : root.cBg2
                border.width: password.activeFocus ? 2 : 1

                Row {
                    anchors.fill: parent
                    anchors.leftMargin: 16
                    spacing: 10
                    Text {
                        anchors.verticalCenter: parent.verticalCenter
                        text: "󰌾"
                        font.family: "JetBrainsMono Nerd Font"
                        font.pixelSize: 16
                        color: root.cMuted
                    }
                    TextInput {
                        id: password
                        width: parent.width - 60
                        anchors.verticalCenter: parent.verticalCenter
                        color: root.cFg
                        font.family: "JetBrainsMono Nerd Font"
                        font.pixelSize: 15
                        echoMode: TextInput.Password
                        passwordCharacter: "●"
                        focus: true
                        clip: true
                        onAccepted: sddm.login(username.text, password.text, sessionModel.lastIndex)
                        Text {
                            anchors.verticalCenter: parent.verticalCenter
                            text: "password"
                            color: root.cMuted
                            font: password.font
                            visible: password.text.length === 0
                        }
                    }
                }
            }

            // login button
            Rectangle {
                width: parent.width
                height: 48
                radius: 14
                color: loginArea.containsPress ? Qt.darker(root.cAccent, 1.15)
                     : loginArea.containsMouse ? Qt.lighter(root.cAccent, 1.05)
                     : root.cAccent
                Text {
                    anchors.centerIn: parent
                    text: "󰍁  unlock"
                    color: root.cBg
                    font.family: "JetBrainsMono Nerd Font Bold"
                    font.pixelSize: 15
                }
                MouseArea {
                    id: loginArea
                    anchors.fill: parent
                    hoverEnabled: true
                    onClicked: sddm.login(username.text, password.text, sessionModel.lastIndex)
                }
            }
        }
    }

    // ── error / status message ──
    Text {
        id: errorMsg
        anchors.horizontalCenter: parent.horizontalCenter
        anchors.top: card.bottom
        anchors.topMargin: 22
        color: root.cRed
        font.family: "JetBrainsMono Nerd Font"
        font.pixelSize: 15
        text: ""
    }

    // ── bottom bar: session + power ──
    Row {
        anchors.right: parent.right
        anchors.bottom: parent.bottom
        anchors.margins: 40
        spacing: 24

        // reboot
        Text {
            text: "󰜉"
            font.family: "JetBrainsMono Nerd Font"
            font.pixelSize: 26
            color: rebootArea.containsMouse ? root.cAccent : root.cMuted
            MouseArea {
                id: rebootArea; anchors.fill: parent; hoverEnabled: true
                onClicked: sddm.reboot()
            }
        }
        // shutdown
        Text {
            text: "󰐥"
            font.family: "JetBrainsMono Nerd Font"
            font.pixelSize: 26
            color: shutdownArea.containsMouse ? root.cRed : root.cMuted
            MouseArea {
                id: shutdownArea; anchors.fill: parent; hoverEnabled: true
                onClicked: sddm.powerOff()
            }
        }
    }

    // session label bottom-left
    Text {
        anchors.left: parent.left
        anchors.bottom: parent.bottom
        anchors.margins: 44
        color: root.cMuted
        font.family: "JetBrainsMono Nerd Font"
        font.pixelSize: 15
        text: "󰧨  Hyprland"
    }

    Component.onCompleted: { if (username.text.length > 0) password.forceActiveFocus(); else username.forceActiveFocus(); }
}
