foreground #d4d4d4
background #161616
selection_foreground #161616
selection_background #8fa1b3
cursor #d4d4d4
cursor_text_color #161616
url_color #8fa1b3
active_border_color #8fa1b3
inactive_border_color #262626
active_tab_background #8fa1b3
active_tab_foreground #161616
inactive_tab_background #1e1e1e
inactive_tab_foreground #6a6a6a
tab_bar_background #161616
visual_bell_color #262626
color0 #262626
color8 #6a6a6a
color1 #bf8b8b
color9 #bf8b8b
color2 #9ab08f
color10 #9ab08f
color3 #c4a97b
color11 #c4a97b
color4 #8fa1b3
color12 #8fa1b3
color5 #b096b0
color13 #b096b0
color6 #8fb3ab
color14 #8fb3ab
color7 #d4d4d4
color15 #d4d4d4
