# MAKO — generated by theme-switch; edit ~/.config/theme-engine/templates/mako.tpl
font=JetBrainsMono Nerd Font 11
width=360
height=140
margin=10
padding=12,16
border-size=2
border-radius=16
anchor=top-right
layer=overlay
max-visible=5
sort=-time

background-color=#{{BG}}f2
text-color=#{{FG}}
border-color=#{{BG2}}
progress-color=over #{{ACCENT}}

default-timeout=6000
group-by=app-name
format=<b>%s</b>\n%b
markup=1
actions=1
icons=1
max-icon-size=48
icon-location=left
history=1
max-history=50

on-button-left=invoke-default-action
on-button-right=dismiss
on-button-middle=dismiss-all
on-touch=dismiss

[grouped]
format=<b>%s</b> (%g)\n%b

[urgency=low]
border-color=#{{BG1}}
text-color=#{{MUTED}}
default-timeout=4000

[urgency=normal]
border-color=#{{BG2}}

[urgency=critical]
border-color=#{{RED}}
text-color=#{{FG}}
default-timeout=0
ignore-timeout=1

[app-name=volume]
history=0
default-timeout=1500

[app-name=brightness]
history=0
default-timeout=1500

[app-name=Screenshot]
default-timeout=3000

[app-name=theme]
history=0
default-timeout=2500

[mode=dnd]
invisible=1

[mode=quiet urgency=low]
invisible=1
[mode=quiet urgency=normal]
invisible=1
