$bg     = rgba(161616ff)
$bg1    = rgba(1e1e1eff)
$fg     = rgba(d4d4d4ff)
$muted  = rgba(6a6a6aff)
$accent = rgba(8fa1b3ff)
$green  = rgba(9ab08fff)
$red    = rgba(bf8b8bff)
$MUTEDHEX = 6a6a6a
$REDHEX = bf8b8b
